### ISSUE TITLE
!Clap doesn't support unicode or custom emotes

### ISSUE THREAD

**Issue by iitalics** [edward-shen/02#8] opened 2018-03-13 19:17 UTC
Using the emote `:gay_pride_flag:` for `!clap` doesn't work, it doesn't recognize it as an emote

**Comment by edward-shen** [comment] 2018-03-13 19:24
Confirmed regression, looks like this is affects all unicode and migrated emojis.

**Comment by edward-shen** [comment] 2018-03-13 20:56
Specifically, the LGBT flag is a combination of multiple emojis, notably, the white flag emoji, a zero width joiner char, and the rainbow emoji. I suspect that the emoji lib dep doesn't properly support similar emojis, or has partial support.

**Comment by edward-shen** [comment] 2018-03-13 20:56
Also looks likes custom emotes do work, but fails when there's a lot of simultaneous parsing. Might be because of the dispatching queue we use.

**Comment by edward-shen** [comment] 2018-03-13 21:13
@erikuhlmann fixed in d3193845589bfc045bb5251943efdf75936e9642. Closing.

**Closed as completed by edward-shen** 2018-03-13 21:13 UTC
Labels: bug
